/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://jitpack.io")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("net.sf.scuba:scuba-smartcards:0.0.19")
    implementation("org.bouncycastle:bcprov-jdk18on:1.72")
    implementation("org.bouncycastle:bcutil-jdk18on:1.72")
    implementation("org.ejbca.cvc:cert-cvc:1.4.13") {
      // excluding this group since it causes build errors
      exclude(group = "org.bouncycastle", module = "bcprov-jdk15on")
    }
    testImplementation("junit:junit:4.13.2")
}

group = "org.jmrtd"
version = "0.7.35"
description = "JMRTD"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
